"""Opportunity card renderer — the single markdown format every engine
must emit. One card per opportunity, following the brief's template."""

from datetime import datetime, timezone


def _evidence_table(evidence: list[dict]) -> str:
    lines = ["| Fact | Source | URL | Raw path | Confidence |",
             "|------|--------|-----|----------|------------|"]
    for ev in evidence:
        lines.append("| {fact} | {source} | {url} | {raw_path} | {confidence} |".format(
            fact=ev.get("fact", ""), source=ev.get("source", ""),
            url=ev.get("url", ""), raw_path=ev.get("raw_path", ""),
            confidence=ev.get("confidence", "")))
    return "\n".join(lines)


def render_card(*, opportunity_type: str, source: str, state: str,
                amount_or_asset: str, confidence: str, decision: str,
                what_exists: str, why_overlooked: str,
                evidence: list[dict], claim_route: dict,
                monetisation: list[str], risks: list[str],
                next_action: str, banner: str = "") -> str:
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    route_lines = "\n".join(
        f"- {label}: {claim_route.get(key, '—')}" for key, label in [
            ("process", "Claim form or court process"),
            ("auction_route", "Auction/bid route"),
            ("attorney_review", "Attorney review needed?"),
            ("registration", "Registration needed?"),
            ("deadline", "Deadline?"),
        ])
    parts = ["# Opportunity Card"]
    if banner:
        parts.append(f"\n> **{banner}**")
    parts.append(f"""
## Summary
- Opportunity type: {opportunity_type}
- Source: {source}
- State: {state}
- Amount / asset: {amount_or_asset}
- Confidence: {confidence}
- Decision: **{decision}**

## What exists
{what_exists}

## Why it may be overlooked
{why_overlooked}

## Evidence
{_evidence_table(evidence)}

## Claim / acquisition route
{route_lines}

## Monetisation route
{chr(10).join(f'- {m}' for m in monetisation)}

## Risk / kill factors
{chr(10).join(f'- {r}' for r in risks)}

## Recommended next action
{next_action}

---
*Generated by TreasureMap US on {generated}. This card is research
material only. It is not legal advice, makes no claim or legal allegation
on anyone's behalf, and does not assert that any party is entitled to any
funds or property.*
""")
    return "\n".join(parts)
